tls:
  certificates:
    - certFile: /run/secrets/tls_cert
      keyFile: /run/secrets/tls_key
  stores:
    default:
      defaultCertificate:
        certFile: /run/secrets/tls_cert
        keyFile: /run/secrets/tls_key

http:
  middlewares:
    secure-headers:
      headers:
        frameDeny: true
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: "strict-origin-when-cross-origin"
        customResponseHeaders:
          X-Powered-By: ""
    rate-limit:
      rateLimit:
        average: 100
        burst: 50
